* Privacy in prompting
** Prompting by proxy
A prompt may be carried out by another user.

- Semiosis token

** Using fake data
e:$PROMPTS/pf-new-file-completion.prompt

Imaginary programming is useful to generate fake data in your programs, and
especially prompts.

Keep in mind that prompts are sending intelligible queries to a remote server
and those queries may be viewed.

Since privacy is an issue, we can instead generate fake data, perhaps
generated from the language model we are about to query.

For example, do we want to list out real files on our system and use that as
input to a prompt?

#+BEGIN_SRC emacs-lisp -n :async :results verbatim code
  (pen-snc \"ls | head -n 10\")
#+END_SRC

- Privacy

** <2021-10-13 Wed> We need to be able to share the output of prompts for the sake of not divulging private information

For example, listing the real contents of our
current directory.

OK, so we want FAKE inputs a lot of the time,
to avoido divulging information.

Therefore, the prompt format should allow you
to specify fake inputs.